### PR TITLE
Start Rework

### PR DESCRIPTION
**Pull request by reteps**

### CODE REVIEW

**Comment by reteps** [comment]
Somehow the commit history got messed up, not sure how. Any ideas how to fix?

**Comment by reteps** [comment]
Note - Why does `batch_size` matter?

**Comment by reteps** [comment]
Note: Even though we automatically select what the best method of saving will be, do we want to provide an override to the user?

**Comment by reteps** [comment]
Note that the possible cases for the user bulk downloading:

+ If the user wants an entry filter, or to move to destination based on CIK, we have to get the URLs from the index files. 
+ If the user only cares about speed, they will not be able to use an entry filter or do these things, but it should still be an option.

Is it possible that even with an entry filter, bulk downloading could be faster? Should that be an option?

**Comment by reteps** [comment]
That commit fixes #159 i think, and also adds the `ultrafast_bulk_save` method.

**Comment by jackmoody11** [comment]
> Somehow the commit history got messed up, not sure how. Any ideas how to fix?

git rebase on upstream master

**Comment by jackmoody11** [comment]
> Note that the possible cases for the user bulk downloading:
> 
> 
> 
> + If the user wants an entry filter, or to move to destination based on CIK, we have to get the URLs from the index files. 
> 
> + If the user only cares about speed, they will not be able to use an entry filter or do these things, but it should still be an option.
> 
> 
> 
> Is it possible that even with an entry filter, bulk downloading could be faster? Should that be an option?

I think that intelligently making this decision would be a nice feature. I would think that we could just read the index file and see if the number of files the user wants to download passes some sort of threshold (like if 50% of all files are going to be downloaded).

**Comment by jackmoody11** [comment]
> Note - Why does `batch_size` matter?

Batch size limits the number of filing links returned. If somebody was only downloading the last 10 10-k filings for a lot of companies this could speed up the time it takes to get the urls since you aren't asking for data you won't use.

**Comment by jackmoody11** [comment]
> Note: Even though we automatically select what the best method of saving will be, do we want to provide an override to the user?

Can you make this into an issue? I don't think we need to tackle this for v0.4.0, but it is something to think about.

**Comment by reteps** [comment]
Rebase wants me to resolve like 100 conflicts, how I can do it better.

**Pull request closed without merging**
