### PR TITLE
Modernize CIK Lookup & Remove Client Base.

### PR DESCRIPTION
**Pull request by reteps**
This is a precursor to v.0.4.0, should be taken care of seperately.

### CODE REVIEW

**Comment by jackmoody11** [comment]
What's the reasoning behind moving CIKLookup to utils?

**Comment by reteps** [comment]
i can move it back if you want,

**Comment by jackmoody11** [comment]
@reteps I am not sure that this needs to be done separately from #162. All of this has been done there and that commit doesn't necessarily need to be the final PR before the release of v0.4.0. Let me know if you disagree and we can reopen.

**Comment by reteps** [comment]
Do this first

**Pull request closed without merging**
