### PR TITLE
CLI daily command fix

### LINKED ISSUE #176: Datetime Error on Daily Fillings
**Describe the bug**
`TypeError: can't compare datetime.datetime to datetime.date.`

**To Reproduce**
1. `$ secedgar daily -d 20210203`
2. See error
```
    elif self._date < datetime.date(1998, 3, 31):
TypeError: can't compare datetime.datetime to datetime.date
```

**Expected behavior**
Download daily fillings

**Desktop (please complete the following information):**
```
Arch Linux 5.10.7-arch1-1
Python 3.9.1

Package           Version
----------------- ---------
aiohttp           3.7.3
async-timeout     3.0.1
attrs             20.3.0
beautifulsoup4    4.9.3
certifi           2020.12.5
chardet           3.0.4
click             7.1.2
idna              2.10
lxml              4.6.2
multidict         5.1.0
pip               20.3.3
requests          2.25.1
secedgar          0.3.2
setuptools        51.0.0
soupsieve         2.1
tqdm              4.56.0
typing-extensions 3.7.4.3
urllib3           1.26.3
wheel             0.36.2
yarl              1.6.3


```

### PR DESCRIPTION
**Pull request by jackmoody11**
- [x] closes #176 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] added entry to docs/whatsnew latest version

### CODE REVIEW

**Comment by lolski** [comment]
Still doesn't work as per commit `c05e06d824aa3df3d9334835fbb3bd7d6f6c7fe2` I think:

Screen Shot 2021-04-30 at 8 21 47 AM

**Comment by jackmoody11** [comment]
I will see if I can figure this out. Thanks @lolski.

**Comment by sroussey** [comment]
Is this the reason behind this error:

```Traceback (most recent call last):
  File "/usr/local/bin/secedgar", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/secedgar/cli.py", line 75, in daily
    d = DailyFilings(date=date_cleanup(date))
  File "/usr/local/lib/python3.9/site-packages/secedgar/cli.py", line 26, in date_cleanup
    return datetime.strptime(date, "%Y%m%d") if date is not None else None
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-07-23' does not match format '%Y%m%d'
~/C/e/secedgar ❯❯❯ docker run -it --mount src="$(pwd)/filings",target=/code/filings,type=bind sec-edgar daily "--directory" /code/filings "--date" "20210723"

Traceback (most recent call last):
  File "/usr/local/bin/secedgar", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/secedgar/cli.py", line 76, in daily
    d.save(directory=directory)
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/daily.py", line 137, in save
    self._save_filings(directory,
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_index.py", line 295, in _save_filings
    urls = self._check_urls_exist()
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_base.py", line 98, in _check_urls_exist
    urls = self.get_urls()
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_index.py", line 170, in get_urls
    filings_dict = self.get_filings_dict()
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_index.py", line 140, in get_filings_dict
    idx_file = self._get_master_idx_file(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_index.py", line 118, in _get_master_idx_file
    if self.idx_filename in self._get_listings_directory().text:
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/daily.py", line 84, in idx_filename
    return "master.{date}.idx".format(date=self._get_idx_formatted_date())
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/daily.py", line 104, in _get_idx_formatted_date
    elif self._date < datetime.date(1998, 3, 31):
TypeError: can't compare datetime.datetime to datetime.date```

**Comment by jackmoody11** [comment]
This PR should solve the issue. Finalizing now to get this into v0.4.0-alpha.2.

**Pull request merged**
