### PR TITLE
Threading

### LINKED ISSUE #38: Asynchronous requests.
Currently, sec-edger download one file at a time which is too slow as a user experience. We can have asynchronous requests to make it faster.

### PR DESCRIPTION
**Pull request by reteps**
- [x] closes #38 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] added entry to docs/whatsnew latest version

### CODE REVIEW

**Comment by reteps** [comment]
@jackmoody11

**Comment by jackmoody11** [comment]
@reteps Have you checked if this results in rate limiting when trying to download a lot of filings? I'm not sure if multiprocessing is the right approach in terms of making requests (as opposed to async/await). However, I also don't have much experience with this.

**Comment by reteps** [comment]
Is there a good way to test this?

**Comment by reteps** [comment]
Async await would run into the same issue btw. What this is doing:
```
for url in list:
    async download_url
    async write_url_contents_to_file
```

The only way to provide some sort of slight speedup without rate limiting would be to do
```
for url in list:
    download_url
    async write_url_contents_to_file
```

Of course, if we figure out the rate limit, the `async` task can be limited to that many requests per second.

**Comment by reteps** [comment]
@jackmoody11 do you have discord or text so we could work this out quickly? I am doing all these changes for a project I am anxious to start haha

**Comment by jackmoody11** [comment]
> Is there a good way to test this?
> 
> 
> 
> EDIT: the `test_save` in `test_master` should provide enough different requests to trigger the rate limit, but the test still passed.

All of the tests are currently using mocks, so it won't pick up on rate limiting. We would need to add that functionality to the mocks. However, I'm not sure exactly what that limit looks like.

**Comment by jackmoody11** [comment]
> Async await would run into the same issue btw. What this is doing:
> 
> ```
> 
> for url in list:
> 
>     async download_url
> 
>     async write_url_contents_to_file
> 
> ```
> 
> 
> 
> The only way to provide some sort of slight speedup without rate limiting would be to do
> 
> ```
> 
> for url in list:
> 
>     download_url
> 
>     async write_url_contents_to_file
> 
> ```
> 
> 
> 
> Of course, if we figure out the rate limit, the `async` task can be limited to that many requests per second.

You're right that using async without figuring out the rate limiting would have the same outcome as multiprocessing. The reason why I think it is better is because if we can figure out the rate limiting, async won't have to use more than one core while still having the same result.

**Pull request closed without merging**
