### PR TITLE
BUMP: Bump to v0.3.3

### PR DESCRIPTION
**Pull request by jackmoody11**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] added entry to docs/whatsnew latest version

### CODE REVIEW

**Comment by reteps** [comment]
yea yea looks good but v0.4 alpha when??

**Review by reteps — APPROVED** [review]
im not sure about that space on line 279.... jk looks great

**Comment by jackmoody11** [comment]
> yea yea looks good but v0.4 alpha when??

Once we fix `download_all` and add testing for it.

**Comment by lolski** [comment]
> * DOC: Add SEC note about user agent
@jackmoody11 Hi! This PR doesn't seem to address setting user agent from the `secedgar` CLI interface.

I can create a PR to fix that. Would that be helpful?

**Comment by jackmoody11** [comment]
> > * DOC: Add SEC note about user agent
> 
> 
> 
> @jackmoody11 Hi! This PR doesn't seem to address setting user agent from the `secedgar` CLI interface.
> 
> 
> 
> I can create a PR to fix that. Would that be helpful?

Yes! That would be very helpful.

**Pull request merged**
