### PR TITLE
Fixed datetime bug + updated requirements

### LINKED ISSUE #176: Datetime Error on Daily Fillings
**Describe the bug**
`TypeError: can't compare datetime.datetime to datetime.date.`

**To Reproduce**
1. `$ secedgar daily -d 20210203`
2. See error
```
    elif self._date < datetime.date(1998, 3, 31):
TypeError: can't compare datetime.datetime to datetime.date
```

**Expected behavior**
Download daily fillings

**Desktop (please complete the following information):**
```
Arch Linux 5.10.7-arch1-1
Python 3.9.1

Package           Version
----------------- ---------
aiohttp           3.7.3
async-timeout     3.0.1
attrs             20.3.0
beautifulsoup4    4.9.3
certifi           2020.12.5
chardet           3.0.4
click             7.1.2
idna              2.10
lxml              4.6.2
multidict         5.1.0
pip               20.3.3
requests          2.25.1
secedgar          0.3.2
setuptools        51.0.0
soupsieve         2.1
tqdm              4.56.0
typing-extensions 3.7.4.3
urllib3           1.26.3
wheel             0.36.2
yarl              1.6.3


```

### PR DESCRIPTION
**Pull request by jorgelaranjo**
- [X] closes #176 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] added entry to docs/whatsnew latest version

### CODE REVIEW

**Review by reteps — APPROVED** [review]
ok

**Comment by jackmoody11** [comment]
I think it is probably better for us to handle this by forcing the CLI to read inputs as date rather than datetime (what it is currently doing is datetime.strptime). This more generally applies to the project. Date seems preferable over datetime.

**Comment by reteps** [comment]
I think this can be closed...

**Comment by jorgelaranjo** [comment]
> I think this can be closed...

Was it fixed on the `CLI` already?

**Comment by jackmoody11** [comment]
Fixed in #203

**Pull request closed without merging**
