### PR TITLE
Client fix

### LINKED ISSUE #164: NetworkClient.get_response() calls requests.get() multiple times even on valid response
In secedgar/client/network_client.py:

```
    def get_response(self, path, params, **kwargs):

        ...

        for i in range(self.retry_count + 1):
            response = requests.get(prepared_url, params=params, **kwargs)
            try:
                self._validate_response(response)
            except EDGARQueryError as e:
                # Raise query error if on last retry
                if i == self.retry_count:
                    raise e
            finally:
                time.sleep(self.pause)
        self.response = response
        return self.response
```

Even when the response passes validation, it does not break out of the for loop. Thus even on valid responses, requests,get() will be called multiple times (self.retry_count + 1). Thus, whenever we attempt to call save() on the filings, it makes a number of unnecessary network requests to Edgar.

### PR DESCRIPTION
**Pull request by jackmoody11**
- [x] closes #164, #166
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] added entry to docs/whatsnew latest version

### CODE REVIEW

**Comment by jackmoody11** [comment]
@reteps if you have a more elegant solution to the test I added, would love to hear it.

**Comment by reteps** [comment]
You can set a retries property on a request: https://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request

**Comment by jackmoody11** [comment]
> You can set a retries property on a request: https://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request

Good call. I had heard of this but had to do some googling to find that you can set a backoff factor. This is a much cleaner approach. Thanks!

**Comment by jackmoody11** [comment]
TIL about using [hooks](https://2.python-requests.org/en/master/user/advanced/#id8) with requests. Very nice to know about that.

**Comment by jackmoody11** [comment]
> You can set a retries property on a request: https://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request

@reteps I looked into this a little more and I couldn't find a great way to implement this that is cleaner than what we have. Here is what I tried, if you are curious:

```python
import requests
from requests.adapters import HTTPAdapter


class Client:
    @staticmethod
    def _validate_response(response, **kwargs):
        """Validate that unwanted text not in response text."""
        if "foo" in response.text:
            response.text_exception = Exception("Did not want to find foo in text")
            response.status_code = 404
            print("Calling validate response in foo")
        elif "baz" in response.text:
            response.text_exception = Exception("Did not want to find baz in text")
            response.status_code = 404
            print("Calling validate response in baz")
        return response

    def get(self):
        with requests.Session() as session:
            session.mount("https://bar.com", adapter=HTTPAdapter(max_retries=3))
            resp = session.get("https://bar.com",
                               hooks=dict(response=[self._validate_response]))
            if hasattr(resp, "text_exception") and resp.text_exception:
                raise resp.text_exception
        return resp


if __name__ == "__main__":
    client = Client()
    client.get()
```


I wanted this to call `_validate_response` 3 times, but it seems like the retry isn't happening because the original response has a 200 status_code (which is what is happening when EDGAR returns a page that says something like "Ticker not found").

**Comment by reteps** [comment]
Add the hook to the session not the request:

```python3
    @staticmethod
    def set_404_for_text(response, **kwargs):
        """Validate that unwanted text is not in response text."""
        if "foo" or "baz" in response.text:
            response.status_code = 404
        return response

    def get(self):
        with requests.Session() as session:
            session.hooks['response'].append(set_404_for_text)
            session.mount("https://bar.com", adapter=HTTPAdapter(max_retries=3))
            resp = session.get("https://bar.com")
            resp.raise_for_status()

        return resp
```

**Comment by reteps** [comment]
https://www.geeksforgeeks.org/response-reason-python-requests/

**Comment by jackmoody11** [comment]
@reteps thanks for the help! The only trouble I am having now is mocking the response before the hooks validate the response. I'm not exactly sure what the best way to handle this is, but will look into it.

**Comment by reteps** [comment]
Could you set `response.reason` instead of a custom `edgar` property? May be cleaner, because then the reason will show in raise_for_exception.

**Comment by reteps** [comment]
Can't you just override the validation function to nothing @jackmoody11 to fix the tests

**Comment by jackmoody11** [comment]
> Could you set `response.reason` instead of a custom `edgar` property? May be cleaner, because then the reason will show in raise_for_exception.

This is a good idea. Thanks!

**Review by reteps — APPROVED** [review]

**Review by reteps — DISMISSED** [review]

**Review by jackmoody11 — COMMENTED** [review]
Need to add back pause to validate response if any sort of error.

**Pull request merged**
