### PR TITLE
Add filings

### LINKED ISSUE #181: Filing type
Hello!

First of all, I appreciate letting me use your crawler to download SEC filings. It has been very beneficial.
I was wondering if it is possible to add N-SAR filings (which are mutual fund annual reports) as a filing type ? They are largely used by academics and I believe they are as crucial as 10-K filings, as they are annual reports reported by open-end funds.
The name of the filing type is "NSAR-A" for annual report and "NSAR-B" for semi-annual. 
Please let me know if this is available. Thanks a lot!

### PR DESCRIPTION
**Pull request by wayneroe**
I have found a javascript [source file](https://www.sec.gov/edgar/browse/scripts/lookup-data.min.js?version=1) with a list of filings. I added every filing that wasn't yet present.

I added them with the following procedure:
- I conformed to the previous naming style.
- In the variable names, I removed '-' and replaced '/' or ' ' with '_'
- I deleted double entries and where the .js file differed from the previous code I always left it how it was.

Question:
I have found another [file](https://www.sec.gov/edgar/browse/scripts/index.min.js?version=1.0.6) where the filings are grouped into different "categories" e.g. insider transactions, ownership, Annual & quarterly reports.
Maybe it would make sense to also structure the filings into these categories?

- [x] fixes #181 (#154)
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] added entry to docs/whatsnew latest version

### CODE REVIEW

**Comment by jackmoody11** [comment]
This is great @wayneroe! I didn't realize that you could find a list of the entire filings through this. What webpage did you capture the javascript from?

@reteps How should we take this into account in addition to the filings you added?

**Comment by wayneroe** [comment]
@jackmoody11 I found it while playing around with the [new search functionality](https://www.sec.gov/edgar/browse/?CIK=1318605&owner=exclude). There you can find it on line 18.

**Comment by reteps** [comment]
@jackmoody11 This may be a better list then the one I found, let's use this one. For reference, this is the one I scraped from the PDF: https://github.com/sec-edgar/sec-edgar/blob/f696658ca243c36fd53100386b9fc45b99b11cc4/secedgar/core/filing_types.py

**Comment by reteps** [comment]
@jackmoody11 Should this be merged?

**Comment by jackmoody11** [comment]
@reteps No filing types should be deleted, but yes we should add the other ones too.

**Review by jackmoody11 — APPROVED** [review]
Thanks for your work Wayne!

**Pull request merged**
